Repository There-is-Go-alternative/GoMicroServices, pull requests merged in 2021-10, with the labels that each got.

#36 [Account] Improve Domain & usecase & database layer
  account/domain/account.go
  account/infra/database/memory.go
  account/internal/xerrors/errors.go
  account/main.go
  account/tests/fixtures.go
  account/transport/public/http/handler.go
  account/transport/public/http/server.go
  account/usecase/create.go
  account/usecase/get.go
  account/usecase/usecase.go
Labels: pending, LGTM

#54 [Ads] Add ads's pictures on firebase
  ads/domain/ad.go
  ads/go.mod
  ads/go.sum
  ads/infra/database/firestore.go
  ads/internal/config/config.go
  ads/transport/http/handler.go
  ads/transport/http/server.go
  ads/usecase/create.go
  ads/usecase/update.go
Labels: enhancement, pending

#58 Account open api and clean service
  account/build/Dockerfile
  account/domain/account.go
  account/transport/public/http/handler.go
  account/transport/public/http/router.go
  authentification/go.sum
  funds/build/Dockerfile
Labels: pending

#66 [Ads] Multiple features
  ads/.env
  ads/.gitignore
  ads/domain/ad.go
  ads/go.mod
  ads/go.sum
  ads/infra/database/firestore.go
  ads/internal/error.go
  ads/internal/xerrors/consts.go
  ads/internal/xerrors/errors.go
  ads/main.go
  ads/transport/api/authorize.go
  ads/transport/http/handler.go
  ads/transport/http/server.go
  ads/usecase/buy.go
  ads/usecase/create.go
  ads/usecase/delete.go
  ads/usecase/get.go
  ads/usecase/search.go
  ads/usecase/usecase.go
  docker-compose.yml
Labels: enhancement, pending
